language: node_js
node_js:
  - '10'
  - '12'
before_script: grunt build
script: grunt jasmine
before_install:
  - npm install -g grunt-cli bower
  - bower install
env:
 - CXX=g++-4.8
addons:
 apt:
  sources:
   - ubuntu-toolchain-r-test
  packages:
   - g++-4.8
